run:
  timeout: 5m
  build-tags:
    - e2e
    - mage

linters:
  disable-all: false
  presets:
    - bugs
    - unused
    - complexity
    - format
    - performance
    - style
  enable:
    - gci
  disable:
    - paralleltest
    - nlreturn
    - exhaustivestruct
    - wsl
    - godox
    - scopelint
    - maligned
    - interfacer
    - golint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck

linters-settings:
  gomoddirectives:
    # List of allowed `replace` directives. Default is empty.
    replace-allow-list:
      # FIXME: google/ko requires 0.22, remove when knative will work with 0.22+
      - k8s.io/apimachinery

