run:
  timeout: 5m
  build-tags:
    - e2e
    - mage
    - ignored

linters:
  disable-all: false
  presets:
    - bugs
    - unused
    - complexity
    - format
    - performance
    - style
  enable:
    - gci
  disable:
    - paralleltest
    - nlreturn
    - exhaustivestruct
    - wsl
    - godox
    - scopelint
    - maligned
    - interfacer
    - golint
    - ireturn
    - varnamelen
    - exhaustruct
    - depguard
    # FIXME: remove `containedctx` exclude after fixing knative-sandbox/kn-plugin-event#202
    - containedctx
    # FIXME: consider enabling and fixing
    - revive
    - copyloopvar
    - perfsprint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck

linters-settings:
  gomoddirectives:
    # List of allowed `replace` directives. Default is empty.
    replace-allow-list: []
