run:
  timeout: 5m
  build-tags:
    - e2e
    - mage
    - ignored

linters:
  disable-all: false
  presets:
    - bugs
    - unused
    - complexity
    - format
    - performance
    - style
  enable:
    - gci
  disable:
    - paralleltest
    - nlreturn
    - wsl
    - godox
    - ireturn
    - varnamelen
    - exhaustruct
    - depguard

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck

linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - knative.dev/kn-plugin-event/pkg/*
      - knative.dev/client/pkg/*
  gomoddirectives:
    # List of allowed `replace` directives. Default is empty.
    replace-allow-list: []
