run:
  timeout: 5m

linters:
  disable-all: false
  presets:
    - bugs
    - unused
    - complexity
    - format
    - performance
    - style
  enable:
    - gci
  disable:
    - paralleltest
    - nlreturn
    - exhaustivestruct
    - wsl
    - godox
    - scopelint
    - maligned
    - interfacer
    - golint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck

linters-settings:
  gomoddirectives:
    replace-allow-list:
      # TODO: remove for k8s 0.21+, see: https://github.com/knative/client/pull/1209
      - github.com/go-openapi/spec
      # TODO: remove after merge of https://github.com/knative/client/pull/1390
      - knative.dev/client
