FROM docker.io/library/golang:1.19 AS builder

COPY . /code
WORKDIR /code

RUN go build \
  -o ./build/wathola-forwarder \
  ./vendor/knative.dev/eventing/test/test_images/wathola-forwarder

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

COPY --from=builder /code/build/wathola-forwarder /app/wathola-forwarder

USER 65532

ENTRYPOINT ["/app/wathola-forwarder"]
