# Copyright 2020 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is automagically synced here from github.com/knative-sandbox/knobots

name: 'Security'

on:
  push:
    branches: [ 'main', 'release-*' ]

  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  analyze:
    uses: cardil/knative-actions/.github/workflows/security.yaml@bugfix/acodeql-autobuild
